export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS';


export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_SIGNUP_SUCCESS = 'SET_SIGNUP_SUCCESS';
export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR';
export const SET_SIGNUP_PENDING = 'SET_SIGNUP_PENDING';